[ClassVersion("1.0.0"), FriendlyName("VMLocalGroupMember")]
class Ericsson_VMLocalGroupMember : OMI_BaseResource
{
  [Key] string VMName;
  [Required,EmbeddedInstance("MSFT_Credential")] string LocalAdminCredential;
  [Key] string MemberName;
  [Key] string GroupName;
};